### ISSUE TITLE
spinner bug when package not found (is not in the registry)

### ISSUE THREAD

**Issue by tunnckoCore** [helpers/helper-reflinks#3] opened 2016-05-01 02:22 UTC
to reproduce:
1. add some not existing package as reflink `[fkj34hk5h345h][]`
2. lint.reflinks is true
3. run verb

it shows message, but it appends it to `creating reference links from npm data` on same line

screenshot
![screenshot from 2016-05-01 05-21-02](https://cloud.githubusercontent.com/assets/5038030/14939740/a02b9078-0f5c-11e6-97eb-d4adf68bdb73.png)

**Comment by jonschlinkert** [comment] 2016-05-01 02:28
duplicate of https://github.com/helpers/helper-reflinks/issues/2 lol

**Closed as completed by jonschlinkert** 2016-05-01 02:28 UTC

**Comment by tunnckoCore** [comment] 2016-05-01 02:32
thought of that, but wasn't sure :D

**Comment by jonschlinkert** [comment] 2016-05-01 02:34
weird bug though, I suspect it's something simple
